baseURL = "https://Blackcat1997.github.io/"
languageCode = "en-us"
theme = "hugo-coder-portfolio"
title = "👾TAKEABYTE"
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Be creative." # Author's name.
    info = "Feel the loneliness." # Author's job title or info.
    description = "FOR2049X" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
     # Contain the path of the optionnal avatar in the static folder.



    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    #thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/Blackcat1997"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/Blackcat1997X"
[[params.social]]
    name = "Email"
    weight = 3
    url = "amaze2333@gmail.com"

   
# Menu links
[[menu.main]]
    name = "Devs"
    weight = 1
    url  = "devs"
[[menu.main]]
    name = "Books"
    weight = 2
    url = "books"
[[menu.main]]
    name = "movies"
    weight = 3
    url = "movies"
[[menu.main]]
    name = "others"
    weight = 5
    url = "others"
[[menu.main]]
    name = "About"
    weight = 6
    url = "about"



